### ISSUE TITLE
Our docker container fails to run changelog

### ISSUE THREAD

**Issue by mogyoro** [bkartyas/changelog#4]
Eventlet workers fail to boot due to an exception in virtualenv.
(Prezi's image works, see [Setup docker](https://github.com/bkartyas/changelog#setup---docker) )

**Output:**
C:\Users\Balazs>docker run -p 5000:5000 -it bkartyas/changelog
Starting gunicorn with 2 workers, listening on 0.0.0.0:5000
[2017-04-19 22:41:54 +0000] [5] [INFO] Starting gunicorn 19.7.1
[2017-04-19 22:41:54 +0000] [5] [INFO] Listening at: http://0.0.0.0:5000 (5)
[2017-04-19 22:41:54 +0000] [5] [INFO] Using worker: eventlet
[2017-04-19 22:41:54 +0000] [10] [INFO] Booting worker with pid: 10
[2017-04-19 22:41:54 +0000] [13] [INFO] Booting worker with pid: 13
[2017-04-19 22:41:54 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 102, in init_process
    self.patch()
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/gunicorn/workers/geventlet.py", line 91, in patch
    hubs.use_hub()
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 70, in use_hub
    mod = get_default_hub()
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/eventlet/hubs/__init__.py", line 38, in get_default_hub
    import eventlet.hubs.epolls
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/eventlet/hubs/epolls.py", line 27, in <module>
    from eventlet.hubs.hub import BaseHub
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 23, in <module>
    from eventlet.support import greenlets as greenlet, clear_sys_exc_info, monotonic, six
  File "/opt/changelog/virtualenv/local/lib/python2.7/site-packages/eventlet/support/monotonic.py", line 167, in <module>
    raise RuntimeError('no suitable implementation for this system')
RuntimeError: no suitable implementation for this system
[2017-04-19 22:41:54 +0000] [13] [INFO] Worker exiting (pid: 13)
Loading user-specified settings from ./custom_settings.py
Starting with settings {'ALCHEMY_URL': 'sqlite:///changelog.db', 'LISTEN_HOST': '127.0.0.1', 'USE_SENTRY': False, 'LISTEN_PORT': 5000, 'SENTRY_DSN': None}
[2017-04-19 22:42:24 +0000] [5] [INFO] Shutting down: Master
[2017-04-19 22:42:24 +0000] [5] [INFO] Reason: Worker failed to boot.

**Comment by bkartyas** [comment]
It's probable caused because of this: https://github.com/eventlet/eventlet/issues/401

**Comment by temoto** [comment]
Please try new eventlet version. Hopefully it fixes this problem

`pip install https://github.com/eventlet/eventlet/archive/b756447bab51046dfc6f1e0e299cc997ab343701.zip`
